#!/usr/bin/env bash

export EXTRA_CONTAINER_OPTS="\
    --detach \
    --init
"

$(dirname $0)/run-container $@

source $(dirname $0)/common.sh
docker exec \
  -d \
  $CONTAINER_NAME \
  /bin/sh -c \
  "sudo service postgresql start"

