#!/usr/bin/env bash

list=(` ls | grep machine | awk '{split($0, arr, "-"); print arr[2]}' `)
echo "#######################################################"
echo "Which machine you want to enter?"
for((i=0;i<${#list[@]};i++));
do
    echo "$i. ${list[i]}"
done

while true 
do
    read -p "Index: " ind

    if [ ! -z "${list[ind]}" ] && [ $ind -ge 0 ];
    then
        echo "you are going to enter ${list[ind]}"
        break
    else
        echo "Key wrong syntax"
    fi
done

cd machine-${list[ind]}


arr=(` docker-compose ps | awk 'NR>2 {split($0,arr," "); print arr[1]}' `)
echo "#######################################################"
echo "Which container you want to enter?"
for((i=0;i<${#arr[@]};i++));
do
    echo "$i. ${arr[i]}"
done

while true 
do
    read -p "Index: " ind

    if [ ! -z "${arr[ind]}" ] && [ $ind -ge 0 ];
    then
        echo "you are going to enter ${arr[ind]}"
        break
    else
        echo "Key wrong syntax"
    fi
done

source .env
docker exec \
    --env TERM=xterm-256color \
    --interactive \
    --tty \
    --user $CONTAINER_USER \
    ${arr[ind]} \
    enter-container-shell