#!/bin/bash
export WORKSPACE=$PWD

./ubuntu-firewall-allow-host-ports

cd $WORKSPACE/machine-main && docker-compose up --build --detach
cd $WORKSPACE/machine-hotstandby && docker-compose up --build --detach

cd $WORKSPACE && ./check-status
