#!/bin/bash
export WORKSPACE=$PWD


list=(` ls | grep machine | awk '{split($0, arr, "-"); print arr[2]}' `)

for((i=0;i<${#list[@]};i++));
do
    cd $WORKSPACE/machine-${list[i]} && docker-compose ps
done


