class Const():
    ERROR = "Error"
    INFO = "Info"
    CONNECTION_DATA_FILE = "tmp/connection_data.json"
    SUCCESS = "Success"
    PROJECT_DIR_FILE = "tmp/project_dir.json"
    FAILED = "Failed"
    DEPLOY = "Deploying"
    EMPTY = ""
    CLOSING = "Closing"
    SLEEPING = "Sleeping"
    PROJECT_DIR = 'projectDir'
    DATA = 'data'
    MACHINE = 'machine'
    DOCKER_COMPOSE_TYPE = 'dockerComposeType'
    DEPLOY_STATUS = 'deployStatus'
    BACKGROUND_JOB_RUNNING = "background job running"
    TWO_SPACE_OR_MORE = '\s\s\s+'
    LOST_CONNECTION = "Lost Connection"
